"""add knowledge feedback and notifications

Revision ID: d91787af74d4
Revises: abb997729ac3
Create Date: 2026-07-02 18:22:34.445245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91787af74d4'
down_revision: Union[str, Sequence[str], None] = 'abb997729ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_feedback',
    sa.Column('user_id', sa.String(length=64), nullable=False, comment='用户 ID'),
    sa.Column('question', sa.String(length=500), nullable=False, comment='用户提问'),
    sa.Column('answer_preview', sa.String(length=500), nullable=False, comment='系统回答预览'),
    sa.Column('rating', sa.SmallInteger(), nullable=False, comment='1=有用, -1=无用, 0=未评价'),
    sa.Column('comment', sa.String(length=1000), nullable=False, comment='用户文字反馈'),
    sa.Column('intent', sa.String(length=50), nullable=False, comment='检索意图'),
    sa.Column('channels', sa.String(length=100), nullable=False, comment='使用的检索通道'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_feedback_rating', 'knowledge_feedback', ['rating'], unique=False)
    op.create_index('ix_knowledge_feedback_user', 'knowledge_feedback', ['user_id'], unique=False)
    op.create_table('knowledge_notifications',
    sa.Column('doc_name', sa.String(length=256), nullable=False, comment='文档名称'),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='文档类型'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='所属分类'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_notifications_category', 'knowledge_notifications', ['category'], unique=False)
    op.create_index('ix_knowledge_notifications_is_read', 'knowledge_notifications', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_notifications_is_read', table_name='knowledge_notifications')
    op.drop_index('ix_knowledge_notifications_category', table_name='knowledge_notifications')
    op.drop_table('knowledge_notifications')
    op.drop_index('ix_knowledge_feedback_user', table_name='knowledge_feedback')
    op.drop_index('ix_knowledge_feedback_rating', table_name='knowledge_feedback')
    op.drop_table('knowledge_feedback')
    # ### end Alembic commands ###
